### ISSUE TITLE
cannot parse import comment

### ISSUE THREAD

**Issue by gnauq3mg6m64rs2n** [Bogdan-D/go-socks4#1]
go get -u github.com/bdandy/go-socks4
/home/pisya/go/src/github.com/bdandy/go-socks4/socks4.go:1: cannot parse import comment

fix it

**Comment by alex09x** [comment]
?

**Comment by bdandy** [comment]
@gnauq3mg6m64rs2n can't reproduce, please add more details, go version etc.
